#!/usr/bin/env python3
import os, sys

folder = ""
if len(sys.argv) > 1:
    folder += "\\" + sys.argv[1]

wslenv = os.environ['WSLENV']
pwd = os.environ['PWD']
pwd = pwd.replace("/","\\")
print("code \""+os.environ['WSLENV']+pwd+folder+"\"")
os.system("code \""+os.environ['WSLENV']+pwd+folder+"\"")
